#!/bin/sh
source /etc/profile
HADOOP_HOME='/opt/cloudera/parcels/CDH-5.3.4-1.cdh5.3.4.p0.4/'
YESTERDAY=`date -d yesterday +%Y%m%d`
TODAY=`date +%Y%m%d`
CURRENT_DATE=`date +'%Y-%m-%d %H:%M:%S'`

sqoop import --connect jdbc:mysql://172.16.3.195:3306/hyip?tinyInt1isBit=false --username eadmin --password 'EWQTB512Oikf;' --table user_account_charge_detail_new_00 --fields-terminated-by '\001' --where "create_time>=$YESTERDAY and create_time<$TODAY" -m 4 --hive-import  --hive-drop-import-delims --hive-table base.user_account_charge_detail_new --delete-target-dir --hive-overwrite --hive-partition-key dt --hive-partition-value $YESTERDAY --null-string '\\N' --null-non-string '\\N' &>>/home/hive/gds/logs/sqoop/input/$YESTERDAY/user_account_charge_detail_new.log
sqoop import --connect jdbc:mysql://172.16.3.195:3306/hyip?tinyInt1isBit=false --username eadmin --password 'EWQTB512Oikf;' --table user_account_charge_detail_new_01 --fields-terminated-by '\001' --where "create_time>=$YESTERDAY and create_time<$TODAY" -m 4 --hive-import  --hive-drop-import-delims --hive-table base.user_account_charge_detail_new --delete-target-dir --hive-partition-key dt --hive-partition-value $YESTERDAY --null-string '\\N' --null-non-string '\\N' &>>/home/hive/gds/logs/sqoop/input/$YESTERDAY/user_account_charge_detail_new.log
sqoop import --connect jdbc:mysql://172.16.3.195:3306/hyip?tinyInt1isBit=false --username eadmin --password 'EWQTB512Oikf;' --table user_account_charge_detail_new_02 --fields-terminated-by '\001' --where "create_time>=$YESTERDAY and create_time<$TODAY" -m 4 --hive-import  --hive-drop-import-delims --hive-table base.user_account_charge_detail_new --delete-target-dir --hive-partition-key dt --hive-partition-value $YESTERDAY --null-string '\\N' --null-non-string '\\N' &>>/home/hive/gds/logs/sqoop/input/$YESTERDAY/user_account_charge_detail_new.log
sqoop import --connect jdbc:mysql://172.16.3.195:3306/hyip?tinyInt1isBit=false --username eadmin --password 'EWQTB512Oikf;' --table user_account_charge_detail_new_03 --fields-terminated-by '\001' --where "create_time>=$YESTERDAY and create_time<$TODAY" -m 4 --hive-import  --hive-drop-import-delims --hive-table base.user_account_charge_detail_new --delete-target-dir --hive-partition-key dt --hive-partition-value $YESTERDAY --null-string '\\N' --null-non-string '\\N' &>>/home/hive/gds/logs/sqoop/input/$YESTERDAY/user_account_charge_detail_new.log
sqoop import --connect jdbc:mysql://172.16.3.195:3306/hyip?tinyInt1isBit=false --username eadmin --password 'EWQTB512Oikf;' --table user_account_charge_detail_new_04 --fields-terminated-by '\001' --where "create_time>=$YESTERDAY and create_time<$TODAY" -m 4 --hive-import  --hive-drop-import-delims --hive-table base.user_account_charge_detail_new --delete-target-dir --hive-partition-key dt --hive-partition-value $YESTERDAY --null-string '\\N' --null-non-string '\\N' &>>/home/hive/gds/logs/sqoop/input/$YESTERDAY/user_account_charge_detail_new.log
sqoop import --connect jdbc:mysql://172.16.3.195:3306/hyip?tinyInt1isBit=false --username eadmin --password 'EWQTB512Oikf;' --table user_account_charge_detail_new_05 --fields-terminated-by '\001' --where "create_time>=$YESTERDAY and create_time<$TODAY" -m 4 --hive-import  --hive-drop-import-delims --hive-table base.user_account_charge_detail_new --delete-target-dir --hive-partition-key dt --hive-partition-value $YESTERDAY --null-string '\\N' --null-non-string '\\N' &>>/home/hive/gds/logs/sqoop/input/$YESTERDAY/user_account_charge_detail_new.log
sqoop import --connect jdbc:mysql://172.16.3.195:3306/hyip?tinyInt1isBit=false --username eadmin --password 'EWQTB512Oikf;' --table user_account_charge_detail_new_06 --fields-terminated-by '\001' --where "create_time>=$YESTERDAY and create_time<$TODAY" -m 4 --hive-import  --hive-drop-import-delims --hive-table base.user_account_charge_detail_new --delete-target-dir --hive-partition-key dt --hive-partition-value $YESTERDAY --null-string '\\N' --null-non-string '\\N' &>>/home/hive/gds/logs/sqoop/input/$YESTERDAY/user_account_charge_detail_new.log
sqoop import --connect jdbc:mysql://172.16.3.195:3306/hyip?tinyInt1isBit=false --username eadmin --password 'EWQTB512Oikf;' --table user_account_charge_detail_new_07 --fields-terminated-by '\001' --where "create_time>=$YESTERDAY and create_time<$TODAY" -m 4 --hive-import  --hive-drop-import-delims --hive-table base.user_account_charge_detail_new --delete-target-dir --hive-partition-key dt --hive-partition-value $YESTERDAY --null-string '\\N' --null-non-string '\\N' &>>/home/hive/gds/logs/sqoop/input/$YESTERDAY/user_account_charge_detail_new.log
sqoop import --connect jdbc:mysql://172.16.3.195:3306/hyip?tinyInt1isBit=false --username eadmin --password 'EWQTB512Oikf;' --table user_account_charge_detail_new_08 --fields-terminated-by '\001' --where "create_time>=$YESTERDAY and create_time<$TODAY" -m 4 --hive-import  --hive-drop-import-delims --hive-table base.user_account_charge_detail_new --delete-target-dir --hive-partition-key dt --hive-partition-value $YESTERDAY --null-string '\\N' --null-non-string '\\N' &>>/home/hive/gds/logs/sqoop/input/$YESTERDAY/user_account_charge_detail_new.log
sqoop import --connect jdbc:mysql://172.16.3.195:3306/hyip?tinyInt1isBit=false --username eadmin --password 'EWQTB512Oikf;' --table user_account_charge_detail_new_09 --fields-terminated-by '\001' --where "create_time>=$YESTERDAY and create_time<$TODAY" -m 4 --hive-import  --hive-drop-import-delims --hive-table base.user_account_charge_detail_new --delete-target-dir --hive-partition-key dt --hive-partition-value $YESTERDAY --null-string '\\N' --null-non-string '\\N' &>>/home/hive/gds/logs/sqoop/input/$YESTERDAY/user_account_charge_detail_new.log
if [ $? -eq 0 ] ; then
 echo `date +'%Y-%m-%d %H:%M:%S'` >> /home/hive/gds/filewatch/sqoop/input/$YESTERDAY/user_account_charge_detail_new
else exit 1
fi
